name: Generate GitBlog README

# 添加权限配置
permissions:
  contents: write  # 允许读写仓库内容
on:
  workflow_dispatch:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]
  push:
    branches:
      - master
    paths:
      - main.py

jobs:
  sync:
    name: Generate README
    runs-on: ubuntu-latest
    if: github.repository_owner_id == github.event.issue.user.id || github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
          cache: pip
          cache-dependency-path: "requirements.txt"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Generate new md
        run: |
          python main.py ${{ secrets.G_T }} ${{ github.repository }} --issue_number '${{ github.event.issue.number }}'

      - name: Push README
        run: |
          git config --local user.email "309693441@qq.com"
          git config --local user.name "supertiny99"
          git add README.md BACKUP/*.md
          git commit -a -m 'update new blog' || echo "nothing to commit"
          git push || echo "nothing to push"